### ISSUE TITLE
系统管理员界面

### ISSUE THREAD

**Issue by yuxguo** [Community-Member-Management-System/CMMS-Frontend#18]
- 无权限的用户不显示此页面
- 系统管理员只负责接受各种社团创建、更名等申请，并接受或拒绝

**Comment by yuxguo** [comment]
### 添加了：
- 主界面组件`SystemManagement/SystemManagement.vue`，展示未处理的申请和已经处理的申请
- 申请的简略信息组件`SystemManagement/SystemApplicationItem.vue`，展示单个的每条申请的简略信息

### 预留了：
- 监听变量改变时调用的函数
- 前端对分页的支持

### 未完成：
- 申请的详细信息组件（由社团创建申请功能负责人 @enszhou 实现），负责呈现申请者提供的详细信息，并在下方提供`审核通过`和`拒绝`等按钮

**Comment by enszhou** [comment]
完成了创建社团和审核社团请求的页面，由于后端提供的接口参数有限，故界面比较简单。
