### ISSUE TITLE
社团主页的完善

### ISSUE THREAD

**Issue by Censyu** [Community-Member-Management-System/CMMS-Frontend#22]
包括了社团主页中社团活动以及成员信息的获取与显示
需要处理不同用户权限的不同表现

**Comment by enszhou** [comment]
活动创建页面进行了简化以适配后端

**Comment by enszhou** [comment]
- checklist没有使用swap接口，暂时没有实现交换两个todo位置的功能
- 由于后端checklist只提供了一个content字段，为了丰富checklist的功能，我添加了title、detail、time等字段，通过序列化成字符串的方式存入content中，从后端读取时，再反序列字符串

**Comment by enszhou** [comment]
修改社团和创建社团页面进行了合并，其中修改只使用了patch api，未使用put api

**Comment by enszhou** [comment]
成员邀请页面由于过于简单，被集成到社团成员管理页面了，以dialog形式出现

**Comment by enszhou** [comment]
编辑活动按钮还没添加，考虑是否将其放在活动详情页面（仅当登录用户是该活动所属社团的管理员才显示编辑按钮）
