### ISSUE TITLE
社团信息修改、活动信息修改

### ISSUE THREAD

**Issue by Censyu** [Community-Member-Management-System/CMMS-Frontend#24]
如题，详细可以参见 Project > 基本“修改”功能 中的说明

**Comment by enszhou** [comment]
管理员编辑社团功能已经完成，和创建社团页面共用一个组件。添加了睿课网链接字段。

**Comment by enszhou** [comment]
完成了管理员编辑活动的功能，若signed_in_users为空，patch请求时必须移除这个字段（否则后端报错）
