### ISSUE TITLE
系统管理员：审核社团创建页面

### ISSUE THREAD

**Issue by Censyu** [Community-Member-Management-System/CMMS-Frontend#26]
如题
关于系统管理员目前只需要考虑审核社团创建页面即可
可以复用社团创建的页面，添加是否审核通过的按钮

**Comment by enszhou** [comment]
完成了社团审核的详情页面，如果后端让待审核的社团也可以通过`/api/community/{id}`的get方法请求到，那么就不用这个单独的详情页面了，直接跳转到对应community页面即可
